In [12]:
import random
numbers = random.sample(range(500),500)
print('NUMBERS:', numbers)

NUMBERS: [444, 65, 429, 482, 345, 385, 22, 389, 359, 46, 150, 372, 360, 141, 228, 328, 247, 310, 226, 440, 338, 99, 419, 17, 411, 363, 98, 464, 102, 147, 298, 89, 4, 190, 176, 107, 435, 241, 119, 206, 86, 413, 170, 146, 38, 49, 248, 15, 386, 169, 185, 485, 94, 48, 66, 388, 457, 460, 151, 376, 92, 117, 16, 36, 420, 391, 191, 130, 480, 317, 203, 112, 172, 220, 167, 50, 470, 267, 494, 468, 101, 26, 182, 407, 179, 215, 475, 311, 371, 20, 233, 11, 67, 70, 115, 161, 60, 370, 139, 476, 269, 433, 278, 85, 421, 496, 319, 69, 173, 246, 474, 439, 237, 334, 438, 238, 213, 100, 304, 129, 417, 262, 393, 394, 256, 486, 211, 379, 271, 307, 196, 331, 205, 137, 234, 357, 321, 306, 157, 156, 127, 382, 335, 232, 204, 351, 479, 93, 222, 27, 405, 125, 454, 299, 432, 344, 252, 350, 491, 365, 462, 78, 374, 471, 396, 329, 131, 499, 95, 47, 339, 243, 285, 229, 13, 348, 184, 218, 469, 145, 91, 81, 406, 149, 113, 90, 68, 118, 332, 135, 458, 337, 428, 32, 71, 199, 153, 52, 295, 219, 6, 377, 58, 477, 380, 320, 291, 354, 73, 327, 240, 188, 398, 105, 353, 63, 18, 171, 466, 434, 7, 312, 114, 239, 110, 286, 330, 74, 209, 41, 498, 217, 55, 251, 216, 30, 426, 281, 392, 275, 361, 175, 165, 297, 445, 366, 358, 274, 235, 402, 414, 427, 369, 249, 103, 79, 484, 207, 347, 489, 362, 77, 23, 397, 412, 111, 180, 25, 54, 122, 96, 270, 378, 325, 143, 418, 442, 410, 12, 277, 301, 493, 495, 308, 197, 53, 116, 448, 333, 44, 316, 178, 424, 375, 121, 293, 123, 35, 21, 106, 404, 250, 264, 487, 346, 162, 19, 367, 80, 415, 254, 194, 422, 300, 97, 450, 87, 40, 492, 336, 31, 343, 265, 355, 292, 437, 465, 441, 225, 289, 155, 56, 447, 148, 381, 8, 144, 399, 57, 288, 208, 384, 403, 1, 260, 266, 28, 483, 0, 84, 189, 187, 255, 42, 43, 488, 245, 373, 387, 400, 294, 302, 223, 352, 383, 409, 276, 120, 210, 253, 236, 401, 423, 341, 24, 160, 342, 164, 463, 82, 364, 177, 453, 242, 287, 279, 59, 224, 261, 473, 202, 425, 61, 83, 443, 108, 2, 451, 244, 284, 193, 104, 10, 315, 192, 314, 326, 340, 159, 14, 37, 313, 198, 356, 124, 263, 154, 318, 201, 126, 168, 395, 195, 416, 158, 75, 472, 408, 322, 33, 258, 467, 72, 29, 390, 174, 212, 259, 283, 230, 257, 490, 368, 436, 51, 446, 186, 324, 290, 280, 305, 138, 34, 481, 140, 5, 142, 9, 221, 152, 268, 39, 133, 163, 183, 62, 76, 456, 303, 3, 128, 459, 109, 134, 136, 323, 497, 349, 273, 181, 449, 64, 461, 132, 45, 88, 272, 452, 282, 430, 227, 214, 478, 431, 309, 166, 296, 231, 455, 200]

In [13]:
numbers_original = numbers

In [5]:
def selection_sort(numbers):
    # A variable to hold the number of item comparisons
    comparisons = 0
    
    for i in range(len(numbers)-1):
        # Find index of smallest remaining element
        index_smallest = i
        for j in range(i+1, len(numbers)):
            comparisons = comparisons + 1
            if numbers[j] < numbers[index_smallest]:
                index_smallest = j

        # Swap numbers[i] and numbers[index_smallest]
        temp = numbers[i]
        numbers[i] = numbers[index_smallest]
        numbers[index_smallest] = temp

    return comparisons

In [3]:
# Main program to test the selection sort algorithm
# Display the contents of the list
print('UNSORTED:', numbers)

UNSORTED: [466, 280, 208, 42, 232, 345, 325, 377, 401, 135, 15, 264, 476, 65, 457, 160, 290, 240, 161, 429, 70, 255, 399, 136, 424, 85, 234, 444, 132, 121, 395, 225, 72, 214, 93, 31, 308, 356, 217, 311, 7, 447, 239, 8, 44, 464, 133, 299, 143, 363, 186, 24, 392, 212, 479, 20, 409, 81, 480, 493, 260, 461, 73, 224, 289, 427, 334, 279, 178, 472, 329, 403, 157, 76, 351, 348, 433, 57, 309, 219, 262, 448, 330, 230, 324, 244, 247, 236, 67, 16, 364, 443, 53, 147, 439, 98, 487, 397, 114, 68, 38, 291, 371, 163, 94, 167, 286, 293, 478, 204, 459, 347, 445, 49, 181, 475, 164, 237, 454, 91, 388, 61, 354, 190, 77, 140, 372, 283, 74, 407, 162, 485, 22, 419, 47, 209, 254, 130, 302, 142, 423, 441, 369, 468, 113, 46, 106, 387, 339, 281, 33, 320, 373, 331, 124, 361, 285, 32, 412, 156, 23, 370, 318, 389, 275, 300, 253, 467, 298, 154, 218, 149, 367, 394, 297, 82, 64, 34, 102, 463, 313, 492, 115, 282, 257, 360, 276, 211, 357, 5, 123, 398, 349, 80, 301, 169, 456, 83, 134, 442, 271, 432, 336, 158, 151, 270, 390, 426, 458, 246, 36, 438, 152, 71, 60, 40, 37, 25, 411, 341, 437, 12, 306, 196, 112, 213, 391, 431, 171, 27, 452, 221, 92, 473, 194, 435, 258, 490, 400, 497, 333, 243, 465, 421, 88, 303, 43, 185, 138, 359, 450, 168, 107, 96, 470, 413, 263, 310, 120, 110, 9, 396, 495, 39, 205, 201, 122, 481, 277, 384, 187, 192, 273, 294, 420, 386, 41, 346, 206, 375, 198, 165, 84, 498, 449, 321, 265, 177, 376, 268, 29, 405, 245, 312, 119, 3, 28, 6, 90, 150, 118, 21, 69, 182, 494, 288, 323, 131, 418, 249, 332, 278, 180, 78, 197, 393, 337, 378, 0, 374, 410, 317, 343, 350, 199, 469, 335, 342, 63, 153, 139, 30, 319, 404, 484, 220, 228, 416, 292, 366, 125, 250, 18, 51, 55, 58, 368, 242, 428, 340, 382, 129, 89, 233, 352, 111, 422, 137, 95, 109, 314, 408, 362, 1, 59, 75, 128, 471, 322, 215, 238, 189, 4, 430, 252, 126, 496, 256, 26, 175, 460, 446, 210, 227, 383, 365, 251, 173, 108, 48, 179, 434, 2, 380, 101, 145, 166, 99, 170, 222, 327, 235, 87, 316, 97, 344, 259, 127, 269, 66, 54, 477, 385, 184, 159, 62, 56, 86, 11, 307, 261, 338, 274, 414, 14, 451, 193, 266, 10, 172, 216, 482, 296, 79, 100, 499, 328, 104, 203, 453, 483, 141, 17, 116, 202, 35, 295, 486, 272, 491, 315, 191, 455, 358, 462, 304, 287, 188, 183, 406, 489, 241, 50, 381, 19, 117, 223, 474, 305, 284, 402, 326, 436, 415, 248, 146, 417, 176, 148, 174, 200, 105, 226, 267, 229, 195, 379, 231, 207, 425, 103, 155, 488, 440, 144, 45, 353, 13, 355, 52]

In [6]:
# Call the selection_sort() function
comparisons = selection_sort(numbers)

In [8]:
# Display the (sorted) contents of the list
print('Total comparisons: %d' % comparisons)
print('SORTED:', numbers)

Total comparisons: 124750
SORTED: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499]

In [9]:
def insertion_sort(num_list):
    for i in range(1, len(num_list)):
        j = i

        # Insert num_list[i] into sorted part 
        # stopping once num_list[i] in correct position
        while j > 0 and num_list[j] < num_list[j - 1]:
            # Swap num_list[j] and num_list[j - 1]
            temp = num_list[j]
            num_list[j] = num_list[j - 1]
            num_list[j - 1] = temp
            j -= 1

In [16]:
# Create a list of unsorted values    
numbers = numbers_original

In [17]:
# Print unsorted list
print('UNSORTED:', numbers)

UNSORTED: [444, 65, 429, 482, 345, 385, 22, 389, 359, 46, 150, 372, 360, 141, 228, 328, 247, 310, 226, 440, 338, 99, 419, 17, 411, 363, 98, 464, 102, 147, 298, 89, 4, 190, 176, 107, 435, 241, 119, 206, 86, 413, 170, 146, 38, 49, 248, 15, 386, 169, 185, 485, 94, 48, 66, 388, 457, 460, 151, 376, 92, 117, 16, 36, 420, 391, 191, 130, 480, 317, 203, 112, 172, 220, 167, 50, 470, 267, 494, 468, 101, 26, 182, 407, 179, 215, 475, 311, 371, 20, 233, 11, 67, 70, 115, 161, 60, 370, 139, 476, 269, 433, 278, 85, 421, 496, 319, 69, 173, 246, 474, 439, 237, 334, 438, 238, 213, 100, 304, 129, 417, 262, 393, 394, 256, 486, 211, 379, 271, 307, 196, 331, 205, 137, 234, 357, 321, 306, 157, 156, 127, 382, 335, 232, 204, 351, 479, 93, 222, 27, 405, 125, 454, 299, 432, 344, 252, 350, 491, 365, 462, 78, 374, 471, 396, 329, 131, 499, 95, 47, 339, 243, 285, 229, 13, 348, 184, 218, 469, 145, 91, 81, 406, 149, 113, 90, 68, 118, 332, 135, 458, 337, 428, 32, 71, 199, 153, 52, 295, 219, 6, 377, 58, 477, 380, 320, 291, 354, 73, 327, 240, 188, 398, 105, 353, 63, 18, 171, 466, 434, 7, 312, 114, 239, 110, 286, 330, 74, 209, 41, 498, 217, 55, 251, 216, 30, 426, 281, 392, 275, 361, 175, 165, 297, 445, 366, 358, 274, 235, 402, 414, 427, 369, 249, 103, 79, 484, 207, 347, 489, 362, 77, 23, 397, 412, 111, 180, 25, 54, 122, 96, 270, 378, 325, 143, 418, 442, 410, 12, 277, 301, 493, 495, 308, 197, 53, 116, 448, 333, 44, 316, 178, 424, 375, 121, 293, 123, 35, 21, 106, 404, 250, 264, 487, 346, 162, 19, 367, 80, 415, 254, 194, 422, 300, 97, 450, 87, 40, 492, 336, 31, 343, 265, 355, 292, 437, 465, 441, 225, 289, 155, 56, 447, 148, 381, 8, 144, 399, 57, 288, 208, 384, 403, 1, 260, 266, 28, 483, 0, 84, 189, 187, 255, 42, 43, 488, 245, 373, 387, 400, 294, 302, 223, 352, 383, 409, 276, 120, 210, 253, 236, 401, 423, 341, 24, 160, 342, 164, 463, 82, 364, 177, 453, 242, 287, 279, 59, 224, 261, 473, 202, 425, 61, 83, 443, 108, 2, 451, 244, 284, 193, 104, 10, 315, 192, 314, 326, 340, 159, 14, 37, 313, 198, 356, 124, 263, 154, 318, 201, 126, 168, 395, 195, 416, 158, 75, 472, 408, 322, 33, 258, 467, 72, 29, 390, 174, 212, 259, 283, 230, 257, 490, 368, 436, 51, 446, 186, 324, 290, 280, 305, 138, 34, 481, 140, 5, 142, 9, 221, 152, 268, 39, 133, 163, 183, 62, 76, 456, 303, 3, 128, 459, 109, 134, 136, 323, 497, 349, 273, 181, 449, 64, 461, 132, 45, 88, 272, 452, 282, 430, 227, 214, 478, 431, 309, 166, 296, 231, 455, 200]

In [18]:
# Initial call to insertion_sort with index 
insertion_sort(numbers)

In [19]:
# Print sorted list
print('SORTED:', numbers)

SORTED: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499]